### ISSUE TITLE
UI Test failures in GHA

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#1003]
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/494
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/777
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/982
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/910
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/929
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/945 ( Duplicate issue -https://github.com/OpenLiberty/liberty-tools-intellij/issues/972)

**Comment by TrevCraw** [comment]
Closing even though https://github.com/OpenLiberty/liberty-tools-intellij/issues/777 is in progress to clean up the backlog. 777 will be tracked separately.
