### ISSUE TITLE
Support IntelliJ IDEA 2024.3

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#1005]
~Investigate to find any issues with LTI using the 2024.3 EAP release: https://www.jetbrains.com/idea/nextversion/.~

Investigate to find any issues with LTI using the 2024.3 Community and Ultimate editions: https://www.jetbrains.com/idea/download/other.html

This document(https://plugins.jetbrains.com/docs/intellij/api-changes-list-2024.html#20243) helps for 2024.3 support

Open new issues and track them here.

- [x] #1119 
- [x] #1127
- [x] Update compatibility level to 2024.3

**Comment by anusreelakshmi934** [comment]
We reviewed their documentation for any updates and could find out some classes were renamed and some json classes were also removed. Here is the link of the changes - https://plugins.jetbrains.com/docs/intellij/api-changes-list-2024.html.

**Comment by anusreelakshmi934** [comment]
In addition to that, we can see a set of classes are showing as deprecated, once doing runIde. Functionalities are woking as expected. But it shows an error message once doing runIde.


![image](https://github.com/user-attachments/assets/2def5cb1-424f-4b71-96fe-fcff46c68d75)

**Comment by anusreelakshmi934** [comment]
Created These issue as part of migration to 2024.3

- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1118

- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1119

- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1120

**Comment by anusreelakshmi934** [comment]
These issues were also discovered during testing for 2024.3 support.

- [ ] #1118 
- [ ] #1120

**Comment by vaisakhkannan** [comment]
These issues were discovered during testing/investigation for 2024.3 support.

- [ ] #1118 
- [ ] #1120

**Comment by vaisakhkannan** [comment]
Following deprecations were found when I use 2024.3 version for the production build

runReadActionInSmartMode --> https://github.com/OpenLiberty/liberty-tools-intellij/blob/47e9a4ead5efe10090f55b2d6a73c8150373a1fa/src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi/core/ProjectLabelManager.java#L100C56-L100C80
