### ISSUE TITLE
Support the latest release of LCLS (Q4-2024)

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#1006]
Test with LCLS snapshot drivers when available: https://github.com/OpenLiberty/liberty-language-server

Update to final release version once integration is successful.

Check for any regression in LCLS behaviour.
Determine new LCLS behaviour to test and verify it behaves as expected (i.e. support for versionless features).

If any problems are discovered, open issues and track them in this issue.

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/967
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1034
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1035
- [x] #1017
- [x] Update LCLS dependencies to release version `2.2`

**Comment by dessina-devasia** [comment]
Tested version less feature by using LCLS 2.2-SNAPSHOT. Diagnostics and quick fix for the incorrect feature can be identified, indicates it supports the versionless feature.

![image](https://github.com/user-attachments/assets/981fafe3-4e3e-4277-bfae-80b8d1a46c51)

**Comment by dessina-devasia** [comment]
Diagnostics related to adding the same feature multiple times are functioning correctly with LCLS 2.2-SNAPSHOT.

![image](https://github.com/user-attachments/assets/41f31315-8a5f-4b41-a096-d5ed05730efd)

**Comment by dessina-devasia** [comment]
Tested issue [#](https://github.com/OpenLiberty/liberty-tools-intellij/issues/965) using LCLS 2.2-SNAPSHOT in LTI.

Existing features are not showing in the suggestion list indicates the issue is solved.

![image](https://github.com/user-attachments/assets/286d1557-f833-4303-a589-34b0d01ef549)

**Comment by dessina-devasia** [comment]
Tested the cases mentioned in the comment [https://github.com/OpenLiberty/liberty-language-server/issues/280#issuecomment-2317684378] using LCLS 2.2-SNAPSHOT in LTI.

All the points mentioned in the comments are working fine.

**Comment by dessina-devasia** [comment]
Tested issue #1017 using LCLS 2.2-SNAPSHOT in LTI.

The Diagnostics are displayed for invalid values if there is an empty line before the variable in server.env, indicates the issue has been resolved.

![image](https://github.com/user-attachments/assets/59fc8dcb-dcbe-483f-9c4d-38c880c1ad16)

![image](https://github.com/user-attachments/assets/d954a97b-48de-46a1-8fea-f2cc50c5ab0a)
