### ISSUE TITLE
Address compatibility issues with IntelliJ IDEA version 2024.3

### ISSUE THREAD

**Issue by dessina-devasia** [OpenLiberty/liberty-tools-intellij#1175]
The compatibility issues are caused by the use of APIs marked for removal, deprecated APIs, experimental APIs, and violations of override-only API usage. 

Following issues to be addressed:
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1118 
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1120 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1176
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1177
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1178
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1179
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1180
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1181
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1182
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1183
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1184
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1185
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1186
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1187
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1188
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1189
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1190
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1191
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1192
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1193
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1197
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1198
