### ISSUE TITLE
Language Server Integration EPIC

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#280]
EPIC for tracking critical items related to language server integration:

**Diagnostics (bug-fixes):**
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/85
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/275
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/270
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/259
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/258

~~- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/268~~ Not a bug - may be limitation of IntelliJ, see the comment on issue.

**Quick-fixes:**
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/194
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/282
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/81
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/283
- [x] #122 (We need to compile a list of Eclipse LSP4MP quick-fixes that need porting to IntelliJ)
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/103

**must-fix bugs**:
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/287
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/288
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/336
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/329
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/342
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/328
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/367

**should-fix bugs**: 
https://github.com/OpenLiberty/liberty-tools-intellij/issues?q=is%3Aissue+is%3Aopen+label%3Ashould-fix+label%3A%22language+client%22

**Comment by turkeylurkey** [comment]
Removed issues unrelated to the language server client.
