### ISSUE TITLE
Transform the Jakarta EE code actions on to a common extension point shared with MicroProfile.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#578]
This epic covers a subset of the work required to unify the implementation of MicroProfile and Jakarta EE code action participants that can be completed without the refactored Eclipse LSP4MP/LSP4Jakarta language server client APIs being available.

- Update the code action participant extension point so that it can be used by any Java language server (MicroProfile, Jakarta EE, etc...).
- Refactor the code for loading and invoking code action participants so that it can be shared with MicroProfile and Jakarta EE.
- Replace calls to the JakartaCodeActionHandler with calls to the shared CodeActionHandler (MicroProfile version)
- Refactor all of the Jakarta EE code action participants to implement the common extension point. This will require some refactoring in order to support deferred resolution of code actions.
- Enable automated tests for Jakarta EE code actions (https://github.com/OpenLiberty/liberty-tools-intellij/issues/476).

Tests for Jakarta EE code actions were not enabled with the 23.0.6 release because the code actions were not delivered. As development of code actions is completed, the tests can and should be incrementally enabled. The code action test code is still as-is from the initial porting from the LSP4Jakarta project and will need some adjustments to the expected output for the Liberty Tools for IntelliJ.

For reference, the initial work for integration of Jakarta EE code actions in Liberty Tools for IntelliJ was completed under this GitHub issue here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/103.

As a starting point for development, I created a feature branch: https://github.com/OpenLiberty/liberty-tools-intellij/tree/code-action-unification which contains the PoC for unifying MicroProfile and Jakarta EE code actions. Development for this epic was initially delivered to this feature branch. Feature development should continue on this branch: https://github.com/OpenLiberty/liberty-tools-intellij/tree/code-action-unification-2.

**Comment by TrevCraw** [comment]
Items for the epic:

- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/511
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/512
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/513
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/514
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/517
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/522
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/534
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/543
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/577
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/589
- [ ] https://github.com/OpenLiberty/liberty-tools-intellij/issues/593
