### ISSUE TITLE
Update code to use the latest lsp4ij from Microshed

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#592]
There is an lsp4ij branch on Microshed that uses the lsp4ij code from 11/01. 

Update this tool to make use of that. This mainly affects the MicroProfile support (e.g. lsp4mp4ij) but these changes will also affect the other language servers.

Issues required to close this item:

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/431
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/521
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/535
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/587
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/603
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/604
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/605
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/606
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/612
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/622
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/623
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/624
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/625
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/634
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/644
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/648
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/654
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/653 (try after resolving https://github.com/OpenLiberty/liberty-tools-intellij/issues/644)
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/620
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/590
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/671
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/679

This issue is to be marked complete only when the `useLSP4IJ1201` feature branch has been merged into `main`.

After merging, we should check old "language client" bugs to see if the LSP4IJ update has resolved them or not. (Incomplete - work item open to address later: https://github.com/OpenLiberty/liberty-tools-intellij/issues/732)

**Comment by turkeylurkey** [comment]
After merging the latest lsp4mp4ij code and the MicroProfile client code 

1. the MicroProfile support produces diagnostics and completion
2. The Jakarta diagnostics only appear if you perform some other action in the Java file like hover or completion. 
3. The LCLS diagnostics appear in bootstrap.properties after you perform hover or completion.
4. The lemminx diagnostics do appear when you open server.xml.

**Comment by turkeylurkey** [comment]
ToDo:
[ ] - start Jakarta language server when a Java file is opened
[ ] - start the LCLS language server when a properties file is opened

**Comment by turkeylurkey** [comment]
LCLS: 
XML:
diagnostics : ok
xml completion : ok
feature completion in server.xml : todo
Properties:
invalid diagnostic "Unknown property 'default.http.port'"
hover : ok
completion : todo
