### ISSUE TITLE
Update to use the lsp4ij from Jetbrains marketplace

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#608]
The lsp4ij on the Jetbrains marketplace is an IntelilJ plugin.

XML
As a plugin it has certain characteristics defined in plugin.xml (or other xml file imported into plugin.xml). When lsp4ij was used as a jar these characteristics were copied into the `liberty-tools-intellij` plugin.xml (or other xml). We must remove these definitions from LTI to use the marketplace version. Specifically, examine plugin.xml in the lsp4ij plugin source. Extensions such as "server" and "languageMapping" are defined here and hence are not needed in `liberty-tools-intellij`.

Messages
By the same token, the lsp4ij plugin references certain messages when it is building the UI elements. These messages were copied into LTI and must be removed when we use the plugin lsp4ij (remove file LanguageServerBundle.properties).

 - [x] update build.gradle (plugin not jar)
 - [x] update the package names
 - [x] update the xml files
 - [x] remove the messages required by the language server panel
 - [x] support for 2024.1
 - [x] #760
 - [x] #775 
 - [x] #795
 - [x]  FVT of LS features
 - [x] Move this POC to a development branch that is up to date with 24.0.6 release

Work is in progress on branch https://github.com/OpenLiberty/liberty-tools-intellij/tree/useLSP4IJmarket

**Comment by aparnamichael** [comment]
Integration steps: (v0.0.1-20240331-012908)

1. Added LSP4IJ and Telemetry plugin in build.gradle
3. Added dependency of both LSP4IJ and Telemetry plugin in plugin.xml
<depends>com.redhat.devtools.lsp4ij</depends>
<depends>com.redhat.devtools.intellij.telemetry</depends>
4. Removed lsp4ij.xml file
5. Added new factory classes from Paul's branch.(https://github.com/OpenLiberty/liberty-tools-intellij/commit/332fa7fa37021e8e5e69d61b4e86838f6492c3a6)
6. Updated all the imports (org.microshed -> com.redhat)
7. LSP4IJUtils class method 'toLocation' is removed in the current lsp4Ij plugin version to avoid IntelliJ.modules.java dependency. Commit :  https://github.com/redhat-developer/lsp4ij/commit/a846eeb2f1e24b8857200960aeefd7fa62e062d7
I have copied the changes done in quarkus to our plugin to fix the error due to removal of this method. 
Quarkus commit - https://github.com/redhat-developer/intellij-quarkus/commit/abc6df95d1000855a6e918576e12ad1430a76213

**Comment by aparnamichael** [comment]
List of exceptions and issues after integrating LSP4IJ plugin.
https://ibm.ent.box.com/notes/1517761965209

**Comment by aparnamichael** [comment]
I started work by deleting LanguageServerBundle.properties and then ran the extension. While running the extension, I have encountered import errors(org.microshed -> com.redhat) in a few classes. I have resolved those errors by changing those import statements then re-ran the extension. Then I encountered the ClassNotFoundException for few of the classes: 

**Caused by: java.lang.ClassNotFoundException: com.redhat.devtools.lsp4ij.LSPIJUtils PluginClassLoader(plugin=PluginDescriptor(name=Liberty Tools, id=open-liberty.intellij, descriptorPath=plugin.xml, path=~/Documents/Devex/Codebase/liberty-tools-intellij/build/idea-sandbox/plugins/liberty-tools-intellij, version=24.0.3, package=null, isBundled=false), packagePrefix=null, state=active)**

**Comment by aparnamichael** [comment]
Added support in IntelliJ 2024.1.1: 

- merged the changes from[ useLSP4IJ-005 ](https://github.com/OpenLiberty/liberty-tools-intellij/tree/useLSP4IJmarket_2024.1_intellij_Support)branch in to aparnamichael/issue608_2024intellij_support.

**Comment by aparnamichael** [comment]
UI test status in LSP4IJ plugin integrated branch.

1. All the windows tests are passing.
2. In Linux 3 tests are failing. 
* [GradleSingleModJakartaLSTest](file:///Users/aparnacmichael/Downloads/linux-test-report-3/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModJakartaLSTest.html). [testJakartaQuickFixInJavaPart()](file:///Users/aparnacmichael/Downloads/linux-test-report-3/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModJakartaLSTest.html#testJakartaQuickFixInJavaPart())
* [GradleSingleModMPLSTest](file:///Users/aparnacmichael/Downloads/linux-test-report-3/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.html). [testMPQuickFixInJavaFile()](file:///Users/aparnacmichael/Downloads/linux-test-report-3/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.html#testMPQuickFixInJavaFile())
* [GradleSingleModMPProjectTest](file:///Users/aparnacmichael/Downloads/linux-test-report-3/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.html). [testStartWithConfigInDebugModeUsingToolbar()](file:///Users/aparnacmichael/Downloads/linux-test-report-3/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.html#testStartWithConfigInDebugModeUsingToolbar())
3. In Mac, 2 tests are failing.	•	
4. [GradleSingleModMPLSTest](file:///Users/aparnacmichael/Downloads/mac-test-report-2/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.html). [initializationError](file:///Users/aparnacmichael/Downloads/mac-test-report-2/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.html#initializationError)
* [GradleSingleModMPProjectTest](file:///Users/aparnacmichael/Downloads/mac-test-report-2/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.html). [initializationError](file:///Users/aparnacmichael/Downloads/mac-test-report-2/tests/test/classes/io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.html#initializationError)

**Comment by aparnamichael** [comment]
UI test automation failure in Microprofile quickfix - https://github.com/OpenLiberty/liberty-tools-intellij/issues/775

**Comment by aparnamichael** [comment]
While doing FVT of LS features, found an issue with quick fix. #703, but this issue is reproducible in LTI version 24.0.6 as well.

**Comment by aparnamichael** [comment]
In lsp4ij-market-0.0.2-integration branch, all the tests are success for Linux and Windows environment. Only Mac tests are failing because of known issue.

**Comment by aparnamichael** [comment]
Integrated 0.0.2 lsp4ij in LTI. All the changes are available in lsp4ij-market-0.0.2-integration branch.
