### ISSUE TITLE
Remove use of deprecated APIs

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#61]
Version 0.0.6:

Build of the IDE: IU-221.5787.20
Result: Compatible. 8 usages of deprecated API

Also investigate the use of IntelliJ internal APIs. We should avoid using those if possible.

------------------------------------------------------------------------------------------------------------------------

IDE version - 2024.1.4

[Plugin verifier results](https://plugins.jetbrains.com/plugin/14856-liberty-tools/edit/versions)

1 internal API usage, 20 usages of scheduled for removal API and 43 deprecated API usages.

- [x]  internal API usage - Module.getModuleFilePath() Internal method Module.getModuleFilePath() is invoked in LSPIJUtils.toUri(Module). This method is marked with @ApiStatus.Internal annotation or @IntellijInternalApi annotation and indicates that the method is not supposed to be used in client code.
- [x] #846
- [x] #847

**Comment by kathrynkodama** [comment]
Version 0.0.8

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/26146482/208461716-06914b7e-2d21-4caf-a837-9a7b9dbdd664.png">
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/26146482/208461882-8d17bc31-4107-4512-af02-fe9af20fabbf.png">
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/26146482/208461957-156612c0-55d6-4c8a-bd52-a70ee931055d.png">

**Comment by turkeylurkey** [comment]
Internal APIs:

- [ ] Module.getModuleFilePath()
- [ ] ComponentManager.instantiateClass(Class, PluginId)
- [ ] MavenServerManager.getMavenHomeFile(String)

Deprecated APIs: before removing a deprecated API we should analyze its effect on the earliest version of the IDE which supports this plugin.

**Comment by aparnamichael** [comment]
Internal API usage - Module.getModuleFilePath() 

As per the plugin verifier result, this internal method is used inside LSP4IJUtils class and from our next release onwards the LSP4IJUtils class which we are going to use is from the LSP4IJ plugin. So would't be able to fix this.
