### ISSUE TITLE
Continuous integration of the Red Hat LSP4iJ plug-in.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#666]
As Liberty Tools for IntelliJ transitions from the MicroShed version of LSP4iJ on to the common shared plug-in being built from https://github.com/redhat-developer/lsp4ij we should consider automation for continuous integration of this plug-in. There are nightly builds being published here: https://plugins.jetbrains.com/plugin/23257-lsp4ij/versions.

Can we automate the detection of new nightly builds of LSP4iJ and then integrate and test with Liberty Tools for IntelliJ? This would provide us with constant feedback and provide early warning if something breaks, so that we may act on it sooner. Perhaps this could even be triggered by a PR push to the main branch of LSP4iJ and the automation first builds the LSP4iJ plug-in from the current state of that repository.

---

Tasks for this Epic (as of July 11th)

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/756 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/757 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/758 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/783
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/793
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/845 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/866
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/759 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/815 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/868 
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/889 
- [x] #895
- [x] #896

**Comment by anusreelakshmi934** [comment]
We're aiming to automate GHA workflows for daily cron jobs, facilitating the initiation of lsp4ij integration builds. Our current focus involves extracting details about all opened PRs in the Red Hat lsp4ij repository. Then, we'd pull the merge commit of each open PR and build lsp4ij from the corresponding checked-out branches.
Additionally, we intend to execute lsp4ij integration builds using the lsp4ij main branch atop the open PRs. This approach accommodates scenarios where a PR might be opened and merged before our cron job executes.

**Comment by TrevCraw** [comment]
All items complete.
