### ISSUE TITLE
Support IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#684]
Beta available: https://blog.jetbrains.com/idea/2024/03/intellij-idea-2024-1-beta/
Development branch: https://github.com/OpenLiberty/liberty-tools-intellij/tree/useLSP4IJ-005

This should address the following issues:

**Must complete**
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/706
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/711
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/717
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/720
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/721
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/722
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/735

**Should complete**
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/694
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/699
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/723

**Comment by turkeylurkey** [comment]
Likely some fixes needed.

**Comment by turkeylurkey** [comment]
Merged
