### ISSUE TITLE
Determine how we should activitely monitor changes being made to LSP4iJ.

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#802]
Certain changes being made to LSP4iJ may have a significant impact on Liberty Tools for IntelliJ and we want to know about those changes early so that we can provide feedback and/or plan for how to deal with them in our plug-in.

This item is for investigating how to automate alerts on changes to LSP4iJ.

Things to consider:

alerts on PRs?
should we get notified of updates in issues? GitHub may have automation for this.
notify in e-mail? Slack?
high or low volume of alerts? what is realistic?
Determine ideal solution and determine an MVP solution to implement.

Resource for Slack/GitHub integration: https://github.com/integrations/slack

Work items:

 

- [x]  Slack channel alert to remind about the LSP4IJ kanban board status.
- [x]   Send notification in slack channel on PR creation in LSP4IJ repo - https://github.com/redhat-developer/lsp4ij. (https://github.com/OpenLiberty/liberty-tools-intellij/issues/803)
- [x]   Define the response process for the team to handle the slack alerts
(https://github.com/OpenLiberty/liberty-tools-intellij/issues/810)
- [x]  Define a plan for monitoring the lsp4mp4ij component of IntelliJ Quarkus (just need a simple reminder, similar to the kanban board status reminder)
- [x]  Send a Slack Message to Channel if There Are No New, Updated, or Closed PRs in the Current Run (https://github.com/OpenLiberty/liberty-tools-intellij/issues/848)

**Comment by vaisakhkannan** [comment]
For Workitem 1: Slack channel alert to remind about the LSP4IJ kanban board status.
Kanban board of Lsp4Ij to check the issues and status of their work- https://github.com/orgs/redhat-developer/projects/23/views/1?filterQuery=repo%3A%22redhat-developer%2Flsp4ij%22

This reminder will run every Wednesday at 7 pm IST.

<img width="616" alt="Screenshot 2024-06-07 at 2 20 53 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/dfd12888-3a14-4570-af52-23061f5f2fa5">

One thing to ensure is that notification settings are configured to receive All Messages for the channel.

![39449766-7cfc-4950-a351-a37fca95bdab-2](https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/18e144ff-54ee-4c48-af4e-efc9413439d0)

**Comment by vaisakhkannan** [comment]
### For Workitem 2 - The approach is currently Working and more acceptable
  **Step1**: Create a Slack App:Go to Slack API and create a new app for your workspace. Navigate to the "Incoming Webhooks" section and activate it. Add the app to our desired channel to obtain the Webhook URL.    
  **Step 2**: Create a GitHub Actions Workflow: Create a Workflow File: In our GitHub repository, create a new file under the .github/workflows/ directory, e.g., .github/workflows/slack-notifications.yml.     
  **Step 3**: Use API calls to fetch information about new pull requests in the repository and send notifications to Slack.      
  **Step 4**: Add Secrets to GitHub Repository: Add Slack Webhook Secret:In our GitHub repository, go to "Settings" -> "Secrets" and add a secret named SLACK_WEBHOOK_URL with the value of your Slack Webhook URL.      
  **Step 5**: Customize GitHub API Request: Customize GitHub API Request:Customize the GitHub API request in the workflow file based on our needs. We may want to filter pull requests based on labels, states, or other criteria.      
  **Step 6**: Commit and Push Changes: Commit and Push Changes:Commit the new files (the workflow file) and push them to the GitHub repository.      
  **Step 7**: Verify Workflow Execution: Verify Workflow Execution:After pushing the changes. Check the Actions tab in your GitHub repository to verify that the workflow runs successfully. ( If we require Slack notifications on a regular basis, we'll need Cron job schedules and must verify the workflow runs in the Action Tab to ensure everything is functioning correctly.)

**Comment by vaisakhkannan** [comment]
For Workitem 4, I added a reminder as shown in the image below
<img width="796" alt="Screenshot 2024-06-13 at 7 36 36 PM" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/133869023/3d9f7d98-39b2-4217-89ff-e804385fa71a">

I added link in the `component` word --> https://github.com/redhat-developer/intellij-quarkus/tree/main/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij
`Quarkus` --> https://github.com/redhat-developer/intellij-quarkus
`commits` --> https://github.com/redhat-developer/intellij-quarkus/commits/main/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij
