### ISSUE TITLE
LTI 24.0.9: Improve ability to stay current with new versions of LSP4iJ.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#830]
The overall goal of this epic is to improve our ability to stay current with new versions of LSP4iJ.

**LSP development for LTI 24.0.7:**
- [x] Migrate LTI from the embedded Microshed LSP4iJ to using the Red Hat LSP4iJ plugin from the IntelliJ Marketplace. (https://github.com/OpenLiberty/liberty-tools-intellij/issues/608)
- [x] Create and deploy continuous integration workflows which build and test LTI against the latest changes (PRs and pushes to main) to Red Hat LSP4iJ. Enhance LTI workflows with Slack notifications which inform the team of the success or failure of LSP4iJ continuous integration builds. (https://github.com/OpenLiberty/liberty-tools-intellij/issues/666)
- [x] Automate monitoring of activity in the Red Hat LSP4iJ project, generating Slack notifications for new, updated and recently closed PRs. (https://github.com/OpenLiberty/liberty-tools-intellij/issues/802)
- [x] Align LTI with versions of LSP4iJ, LSP4MP4iJ, LSP4MP which satisfy requirements for a release. (https://github.com/OpenLiberty/liberty-tools-intellij/issues/841)

**Remaining LSP 24.0.8 development work, post-24.0.6:**
- Once 24.0.6 is tagged for release, create a development branch from latest main.
- Integrate the latest Red Hat LSP4iJ release on this branch, applying required changes to LTI that were established in the proof-of-concept.
- Upgrade LSP4MP4iJ from Quarkus tools to the latest level that matches the chosen LSP4iJ release (current target is LSP4iJ 0.0.4).
- Integrate enhancements to the workflows for continuous integration and Slack notifications that were established in their proof-of-concepts.
- Stabilize the development branch, working with the community to resolve issues that need to be addressed before LTI can release.
- Once stable, merge the development branch back into main.

**Comment by TrevCraw** [comment]
All items complete.
