### ISSUE TITLE
LTI 24.0.9: Align LSP4iJ, LSP4MP4iJ and LSP4MP for the release.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#841]
Current versions of the components on or being consumed by the LTI development stream:

**LSP4iJ**: 0.0.2
**LSP4MP4iJ**: snapshot taken on an arbitrary day from the Quarkus Tools main branch to match up with LSP4iJ 0.0.2
**LSP4MP**: 0.12.0-SNAPSHOT

============

Regarding LSP4iJ, there are a couple open issues we've been tracking:
https://github.com/redhat-developer/lsp4ij/issues/294
https://github.com/redhat-developer/lsp4ij/issues/324

We would prefer to resolve https://github.com/redhat-developer/lsp4ij/issues/294 before releasing and through testing we may identify additional issues that would impact the LTI release. This would require moving up to a future release of LSP4iJ (0.3.0?, 0.3.1?) which contains the fixes we require. That is the ideal outcome. We should get an understanding of what is likely to be available from LSP4iJ in the near future and assess whether that will be adequate from an LTI release.

============

Regarding LSP4MP4iJ, we should ideally be basing our snapshot off a release of Quarkus Tools so that it is easy to map this component back to its original source and also represents a version that Red Hat published to the Marketplace. We should check with the Quarkus Tools team on whether there is a release coming soon that we could align with.

============

Regrading LSP4MP, we prefer to have a dependency on a released version of LSP4MP. Currently we're relying on a snapshot of 0.12.0. We should ask the community whether the 0.12.0 is expected soon. The most recent release at the time of this writing appears to be: https://github.com/eclipse/lsp4mp/releases/tag/0.11.3. If 0.12.0 will not be available soon, we should determine if we can align with LSP4MP 0.11.3. Ideally we would align with LSP4MP 0.12.0 because LSP4MP4iJ is currently pulling in a snapshot of this release.

============

What we actually end up doing here depends very much on the activity in each of these dependencies. I've mostly focused on the ideal outcomes but we may need to consider alternatives in order to move forward.

============
Work items:

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/894
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/914
- [x] Update lsp4mp4ij component to align with Quarkus Tools for IntelliJ release 2.0.0: https://github.com/redhat-developer/intellij-quarkus/releases/tag/2.0.0
- [x] Update LSP4MP to 0.12.0: https://github.com/eclipse/lsp4mp/releases/tag/0.12.0

**Comment by mrglavas** [comment]
@angelozerr I think you're probably aware that we've been copying LSP4MP4iJ from Quarkus Tools for Microprofile support. As we've been working an adoption of LSP4iJ we have been taking snapshots from Quarkus Tools main, but now as we're heading towards a release which will use LSP4iJ 0.2.0 (or later) we're hoping to align with a release of Quarkus Tools if possible. We're curious if a new release might be on the horizon. Similarly, we noticed that Quarkus Tools has a dependency on 0.12.0-SNAPSHOT of LSP4MP and are curious if 0.12.0 might be released soon. We have also been pulling this dependency into our development stream but would want to be picking up a released version of LSP4MP when we release LTI.

**Comment by angelozerr** [comment]
> @angelozerr I think you're probably aware that we've been copying LSP4MP4iJ from Quarkus Tools for Microprofile support. As we've been working an adoption of LSP4iJ we have been taking snapshots from Quarkus Tools main, but now as we're heading towards a release which will use LSP4iJ 0.2.0 (or later) we're hoping to align with a release of Quarkus Tools if possible. We're curious if a new release might be on the horizon. Similarly, we noticed that Quarkus Tools has a dependency on 0.12.0-SNAPSHOT of LSP4MP and are curious if LSP4MP 0.12.0 might be released soon. We have also been pulling this dependency into our development stream but would want to be picking up a released version of LSP4MP when we release LTI.

@mrglavas my previous goal was to create a robust (I hope) release for LSP4IJ but now my main goal is to do a release of IJ Quarkus ASAP to consume LSP4IJ, but before I need to fix some important issues for Qute and after that we will release LSP4MP etc but I cannot give you a date

**Comment by aparnamichael** [comment]
**LSP4MP4IJ - new commits after Jun 4.**

Commits on Aug 26, 2024
- [ ]  [chore(skip-release): set version to 2.0.0](https://github.com/redhat-developer/intellij-            quarkus/commit/26bed75039b119bd3945c3b1ea9a2af766cc5749)

- [ ] [chore: use releases of LSP4MP 0.12.0 + Quarkus LS 0.19.0](https://github.com/redhat-developer/intellij-           quarkus/commit/70bfbd094100ae4f44897ce6dbe46d91f4ccd3c4)

         
Commits on Aug 21, 2024
- [ ]  [fix: set platformOnly to false to collect all extensions in the wizard](https://github.com/redhat-developer/intellij-quarkus/commit/b4967c0789240d7d1dd0e37556028b116262630b)

 Commits on Aug 20, 2024
- [ ] [chore(skip-release): Prepare for 2.0.0](https://github.com/redhat-developer/intellij-quarkus/commit/965fd5a42a0d336890091148917377a49b3a905e)

- [ ]  [fix: bumped telemetry to 1.2.1](https://github.com/redhat-developer/intellij-quarkus/commit/764afaf388cc32b533ffe59407ad7fe544bdf21f)

Commits on Aug 19, 2024
- [ ] [build: Improve Compatibility verification](https://github.com/redhat-developer/intellij-quarkus/commit/cc6a65b496112df3dd7780daa9741d79e221b64e)

Commits on Aug 7, 2024
- [ ] [feat: Workspace symbols for JAX-RS endpoints](https://github.com/redhat-developer/intellij-quarkus/commit/869ead4713157ebc6e15a453df959a3af8ba1cd6)

Commits on Jul 27, 2024
- [ ] [feat: Qute: Cannot locate hyphenated template name](https://github.com/redhat-developer/intellij-quarkus/commit/f55035d2259c5b86537780250eb915cbd51a6180) - qute related changes.

Commits on Jul 13, 2024
- [ ] [fix: Check if record implement TemplateInstance to provide the support](https://github.com/redhat-developer/intellij-quarkus/commit/3114a5eb7032fa1fb3adc9ccf288d7998de951e5) - qute related changes.

Commits on Jul 11, 2024
- [ ] [fix: relax](https://github.com/redhat-developer/intellij-quarkus/commit/8a47098c3e2480db7ed86d252b74d72842489201) [@channel](https://github.com/channel) [conditions for completion/validation (](https://github.com/redhat-developer/intellij-quarkus/commit/8a47098c3e2480db7ed86d252b74d72842489201)[#1359](https://github.com/redhat-developer/intellij-quarkus/pull/1359)[)](https://github.com/redhat-developer/intellij-quarkus/commit/8a47098c3e2480db7ed86d252b74d72842489201)   **Updated MicroProfileReactiveMessagingProvider**

- [ ] [feat: Qute: add support for template records](https://github.com/redhat-developer/intellij-quarkus/commit/4f1e08ec34b019b8d8abeed1517b4794c5332582) **- qute server related changes.**

Commits on Jul 9, 2024
- [ ] [chore: Use Qute LS 0.19.0 SNAPSHOT](https://github.com/redhat-developer/intellij-quarkus/commit/5fc6859f23787bb6e00d71af02ef48d01f3bf74c) **- Qute version change.**

- [ ] [Updated actions version. Added distribution for setup-java actions.](https://github.com/redhat-developer/intellij-quarkus/commit/c66b041b7031d2baaf7738f5989849c07486c0d4) **-  GHA workflow file changes.**

Commits on Jul 8, 2024
- [ ] [fix: allow inject: with constructor class which have arguments](https://github.com/redhat-developer/intellij-quarkus/commit/af4b2999c06eea63d11092d5afa0c8400e897803) **- qute related changes.**

Commits on Jul 4, 2024
- [ ] [fix: Fixed UI tests on Linux and Windows (](https://github.com/redhat-developer/intellij-quarkus/commit/302b78996bca3782f2aee23518c11f1ff3548d0a)[#1349](https://github.com/redhat-developer/intellij-quarkus/pull/1349)[)](https://github.com/redhat-developer/intellij-quarkus/commit/302b78996bca3782f2aee23518c11f1ff3548d0a) **- UI test related changes in IJ quarkus.**

Commits on Jul 1, 2024
- [ ] [fix: Formatting is broken when using simple {}](https://github.com/redhat-developer/intellij-quarkus/commit/b945502df4d169968ffca204e4c3d88d2c100a8b) **- qute related changes.**

Commits on Jun 13, 2024
- [ ] [fix: adapt the new API of LSP4IJ](https://github.com/redhat-developer/intellij-quarkus/commit/7641f57b18a31e9adcd7caff085b08857289e458) **- changes are in quarkus and qute lsp files.**
