### ISSUE TITLE
deprecated API usage

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#847]
Deprecated methods usages (25)
- [x] ExtensionPointName.extensions() (6) **_Fix - Replaced with getExtensionList().stream()_** [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)
- [x] Notification.setListener(NotificationListener) (3) #872 [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)
- [x] ServiceManager.getService(Project, Class) (2)  **_Fix - Replaced with project.getService()_** [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)
- [x] InlayHintsProviderFactory.getProvidersInfo(...) (1) **_Fix to be done in lsp4ij plugin_**
- [x] InlayHintsSink.addInlineElement(...) (1) **_Fix to be done in lsp4ij plugin_**
- [x] FilenameIndex.getFilesByName(...) (1) - **_Fix - Replaced with getVirtualFilesByName() method_** [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/865)
- [x] TerminalView.getInstance(Project) (1) **_Fix is available as part of [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/860)_**
- [x] TerminalStarter.getCode(int, int) (1) **_Fix - Replaced with getTerminal().getCodeForKey()_**
- [x] JediTermWidget.getTerminalStarter() (1) **_Fix - Replaced with getTerminal().getCodeForKey()_**
- [x] Messages.showChooseDialog(...) #861   **_Fix - Replaced with MessageDialog class_** [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/884)
- [ ] UI.PanelFactory.grid() and UI.PanelFactory.panel(JComponent) (3) #874 - **_We are not using these classes in LTI, these deprecated methods are used to add a Microprofile settings option in IntelliJ settings window _** 

Deprecated classes usages (11)
- [x] ProjectTopics (3) [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)
- [x] ServiceManager (2) [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)
- [ ] ComponentPanelBuilder (3)  and PanelGridBuilder (3) #874  **_We are not using these classes in LTI, these deprecated methods are used to add a Microprofile settings option in IntelliJ settings window _** 

Deprecated constructors usages (4)
- [x] Notification.<init>(...) (3)  #872 [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)
- [x] InspectionOptionsPanel.<init>() (1) **_Fix to be done in lsp4ij plugin_**

Deprecated fields usages (3) **_Fix:  Replaced with ModuleListener.TOPIC_**
- [x] ProjectTopics.MODULES (3) [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/875)

**Comment by aparnamichael** [comment]
ExtensionPointName.extensions() (6)

- [ ] Deprecated method ExtensionPointName.extensions() is invoked in CompletionHandler.lambda$completion$3(...)
- [ ] Deprecated method ExtensionPointName.extensions() is invoked in CodeActionHandler.resolveCodeAction(...)
- [ ] Deprecated method ExtensionPointName.extensions() is invoked in PropertiesManagerForJava.collectDefinition(...)
- [ ] Deprecated method ExtensionPointName.extensions() is invoked in DiagnosticsHandler.lambda$collectDiagnostics$7(...)
- [ ] Deprecated method ExtensionPointName.extensions() is invoked in PropertiesManagerForJava.collectHover(...)
- [ ] Deprecated method ExtensionPointName.extensions() is invoked in CodeActionHandler.codeAction(...)

Notification.setListener(NotificationListener) (3)

- [ ] Deprecated method Notification.setListener(NotificationListener) is invoked in ServerMessageHandler.showMessage(...)
- [ ] Deprecated method Notification.setListener(NotificationListener) is invoked in JavaVersionUtil.notifyError(String, Project)
- [ ] Deprecated method Notification.setListener(NotificationListener) is invoked in LibertyGeneralAction.notifyError(String, Project)

UI.PanelFactory.grid() (3)

- [ ] Deprecated method UI.PanelFactory.grid() is invoked in MicroProfilePropertiesView.createDescription(...)
- [ ] Deprecated method UI.PanelFactory.grid() is invoked in LanguageServerView.createDescription(String)
- [ ] Deprecated method UI.PanelFactory.grid() is invoked in MicroProfileJavaView.createDescription(String)

UI.PanelFactory.panel(JComponent) (3)

- [ ] Deprecated method UI.PanelFactory.panel(JComponent) is invoked in MicroProfileJavaView.createDescription(String)
- [ ] Deprecated method UI.PanelFactory.panel(JComponent) is invoked in MicroProfilePropertiesView.createDescription(...)
- [ ] Deprecated method UI.PanelFactory.panel(JComponent) is invoked in LanguageServerView.createDescription(String)

ServiceManager.getService(Project, Class) (2)

- [ ] Deprecated method ServiceManager.getService(Project, Class) is invoked in MicroProfileDeploymentSupport.getInstance(Project)
- [ ] Deprecated method ServiceManager.getService(Project, Class) is invoked in ClasspathResourceChangedManager.getInstance(...)

Messages.showChooseDialog(...) (2)

- [ ] Deprecated method Messages.showChooseDialog(...) is invoked in LibertyProjectAction.actionPerformed(...)
- [ ] Deprecated method Messages.showChooseDialog(...) is invoked in RunLibertyDevTask.actionPerformed(AnActionEvent)

InlayHintsProviderFactory.getProvidersInfo(...) (1)

- [ ] Deprecated method InlayHintsProviderFactory.getProvidersInfo(...) is overridden in class LSPInlayHintProvidersFactory

InlayHintsSink.addInlineElement(...) (1)

- [ ] Deprecated method InlayHintsSink.addInlineElement(...) is invoked in LSPColorProvider.lambda$doCollect$1(...)

FilenameIndex.getFilesByName(...) (1)

- [ ] Deprecated method FilenameIndex.getFilesByName(...) is invoked in LibertyProjectUtil.getBuildFiles(...)

TerminalStarter.getCode(int, int) (1)

- [ ] Deprecated method TerminalStarter.getCode(int, int) is invoked in LibertyActionUtil.executeCommand(...)

JediTermWidget.getTerminalStarter() (1)

- [ ] Deprecated method JediTermWidget.getTerminalStarter() is invoked in LibertyActionUtil.executeCommand(...)

TerminalView.getInstance(Project) (1)

- [ ] Deprecated method TerminalView.getInstance(Project) is invoked in LibertyGeneralAction.getTerminalWidgetWithFocus(...)

**Comment by aparnamichael** [comment]
ComponentPanelBuilder (3)

- [ ] Deprecated class ComponentPanelBuilder is referenced in MicroProfilePropertiesView.createDescription(...)
- [ ] Deprecated class ComponentPanelBuilder is referenced in LanguageServerView.createDescription(String)
- [ ] Deprecated class ComponentPanelBuilder is referenced in MicroProfileJavaView.createDescription(String)
- [ ] 

PanelGridBuilder (3)

- [ ] Deprecated class PanelGridBuilder is referenced in LanguageServerView.createDescription(String)
- [ ] Deprecated class PanelGridBuilder is referenced in MicroProfilePropertiesView.createDescription(...)
- [ ] Deprecated class PanelGridBuilder is referenced in MicroProfileJavaView.createDescription(String)

ProjectTopics (3)

- [ ] Deprecated class ProjectTopics is referenced in PsiMicroProfileProjectManager.<init>(Project)
- [ ] Deprecated class ProjectTopics is referenced in ClasspathResourceChangedManager.<init>(Project)
- [ ] Deprecated class ProjectTopics is referenced in MicroProfileProjectService.<init>(Project)

ServiceManager (2)

- [ ] Deprecated class ServiceManager is referenced in MicroProfileDeploymentSupport.getInstance(Project)
- [ ] Deprecated class ServiceManager is referenced in ClasspathResourceChangedManager.getInstance(...)

**Comment by aparnamichael** [comment]
Notification.<init>(...) (3)

- [ ] Deprecated constructor Notification.<init>(...) is invoked in ViewUnitTestReport.executeLibertyAction(...)
- [ ] Deprecated constructor Notification.<init>(...) is invoked in ViewIntegrationTestReport.executeLibertyAction(...)
- [ ] Deprecated constructor Notification.<init>(...) is invoked in ViewTestReport.executeLibertyAction(LibertyModule)

InspectionOptionsPanel.<init>() (1)

- [ ] Deprecated constructor InspectionOptionsPanel.<init>() is invoked in AbstractDelegateInspectionWithExclusions.createOptionsPanel()

**Comment by aparnamichael** [comment]
ProjectTopics.MODULES (3)

- [ ] Deprecated field ProjectTopics.MODULES is accessed in MicroProfileProjectService.<init>(Project)
- [ ] Deprecated field ProjectTopics.MODULES is accessed in PsiMicroProfileProjectManager.<init>(Project)
- [ ] Deprecated field ProjectTopics.MODULES is accessed in ClasspathResourceChangedManager.<init>(Project)

**Comment by aparnamichael** [comment]
Addressed all the issues except UIPanelFactory class deprecations. We are not using those classes having this deprecation in LTI, these deprecated methods are used to add a Microprofile settings option in IntelliJ settings window. Created new issues for adding these in settings, once we add these in settings we can address this deprecation.

https://github.com/OpenLiberty/liberty-tools-intellij/issues/882
https://github.com/OpenLiberty/liberty-tools-intellij/issues/883
