### ISSUE TITLE
Clean up warnings displayed in the GHA job summary

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#899]
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/856
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/892
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/902

Investigate if there are other warnings to clean up.
