### ISSUE TITLE
Support IntelliJ IDEA 2024.2

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#915]
Investigate to find issues with LTI in 2024.2. Open new issues and track them here.

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/767
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/885
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/911
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1018 [In Progress]
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1019
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1020
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1036
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1087
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1088
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1112
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/1131
