### ISSUE TITLE
Update LCLS version to support 'versionless' features in server.xml

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-intellij#967]
We're encountering the following issues due to the lack of support for the 'version-less' feature in LTI. We expect that these issues will be resolved with the upcoming lemminx update.

- [x] Pull in latest LCLS (either a snapshot or local build) and then compare behaviour to below bugs
- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/966 
- [x]  https://github.com/OpenLiberty/liberty-tools-intellij/issues/965
