### ISSUE TITLE
Investigate Linux build failures

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#982]
In many of the tests in Linux GHA we are encountering various errors like the below ones:

A Build that ran had these failures - https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/10846737003/job/30100325255

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/983

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/988

- [x] https://github.com/OpenLiberty/liberty-tools-intellij/issues/564

- [x] Timed out waiting for message CWWKE0036I in log:/home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools intellij/src/test/resources/projects/gradle/singleModGradleMP/build/wlp/usr/servers/defaultServer/logs/messages.log
From one of the failure videos we can see that the dev mode is not getting started even after waiting for 90 seconds. And it is trying to stop the dev mode after that which fails since the dev mode did not fully started.

- [x] GradleSingleModMPProjectTest > testRunTestsActionUsingDropDownMenu() FAILED
    org.opentest4j.AssertionFailedError: testRunTestsActionUsingDropDownMenu:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.

- [x] GradleSingleModLSTest > testDiagnosticInServerEnv() FAILED
    java.lang.RuntimeException: Hover on text: NONE did not trigger a pop-up window to open

- [x] GradleSingleModMPProjectTest > executionError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2M) for condition function (Failed to find 'Welcome Frame' by 'FlatWelcomeFrame type' in 120s) 

- [x] initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2M) for condition function (Failed to find 'Welcome Frame' by 'FlatWelcomeFrame type' in 120s) 
In GradleSingleModMPSIDProjectTest , GradleSingleModNLTRestProjectTest, MavenSingleModMPProjectTest, MavenSingleModMPSIDProjectTest, 

- [x] GradleSingleModMPProjectTest > testStartWithConfigInDebugModeUsingToolbar() FAILED
    com.intellij.remoterobot.client.IdeaSideException: Wrapped java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location

- [x] GradleSingleModLSTest > testInsertLibertyConfigIntoServerEnv() FAILED
    java.lang.RuntimeException: Unable to insert entry in config file : server.env using text: WLP_LOGGING_CON
    [link](https://github.com/anusreelakshmi934/liberty-tools-intellij/actions/runs/10935053904/job/30356143503#step:10:1019)

**Comment by anusreelakshmi934** [comment]
Issues 983, 988 and 564 were successfully closed. And a [fix](https://github.com/OpenLiberty/liberty-tools-intellij/pull/1049) for the timedout issue was successfully merged. Hence closing this Issue.
